logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: autoconfig,beans,env,info,health,httptrace,loggers,mappings,metrics,sessions,threaddump
  endpoint:
    health:
      show-details: always

server:
  servlet:
    session:
      timeout: 1800
  error:
    whitelabel:
      enabled: false

